// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: match/match/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateMatchInfo struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Matchdate string `protobuf:"bytes,2,opt,name=matchdate,proto3" json:"matchdate,omitempty"`
	Home      string `protobuf:"bytes,3,opt,name=home,proto3" json:"home,omitempty"`
	Away      string `protobuf:"bytes,4,opt,name=away,proto3" json:"away,omitempty"`
	Stadium   string `protobuf:"bytes,6,opt,name=stadium,proto3" json:"stadium,omitempty"`
	Spectator int32  `protobuf:"varint,7,opt,name=spectator,proto3" json:"spectator,omitempty"`
}

func (m *MsgCreateMatchInfo) Reset()         { *m = MsgCreateMatchInfo{} }
func (m *MsgCreateMatchInfo) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMatchInfo) ProtoMessage()    {}
func (*MsgCreateMatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{2}
}
func (m *MsgCreateMatchInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateMatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateMatchInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateMatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMatchInfo.Merge(m, src)
}
func (m *MsgCreateMatchInfo) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateMatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMatchInfo proto.InternalMessageInfo

func (m *MsgCreateMatchInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateMatchInfo) GetMatchdate() string {
	if m != nil {
		return m.Matchdate
	}
	return ""
}

func (m *MsgCreateMatchInfo) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *MsgCreateMatchInfo) GetAway() string {
	if m != nil {
		return m.Away
	}
	return ""
}

func (m *MsgCreateMatchInfo) GetStadium() string {
	if m != nil {
		return m.Stadium
	}
	return ""
}

func (m *MsgCreateMatchInfo) GetSpectator() int32 {
	if m != nil {
		return m.Spectator
	}
	return 0
}

type MsgCreateMatchInfoResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateMatchInfoResponse) Reset()         { *m = MsgCreateMatchInfoResponse{} }
func (m *MsgCreateMatchInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateMatchInfoResponse) ProtoMessage()    {}
func (*MsgCreateMatchInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{3}
}
func (m *MsgCreateMatchInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateMatchInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateMatchInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateMatchInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateMatchInfoResponse.Merge(m, src)
}
func (m *MsgCreateMatchInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateMatchInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateMatchInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateMatchInfoResponse proto.InternalMessageInfo

func (m *MsgCreateMatchInfoResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateMatchInfo struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id         uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Matchdate  string `protobuf:"bytes,3,opt,name=matchdate,proto3" json:"matchdate,omitempty"`
	Home       string `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	Away       string `protobuf:"bytes,5,opt,name=away,proto3" json:"away,omitempty"`
	Stadium    string `protobuf:"bytes,6,opt,name=stadium,proto3" json:"stadium,omitempty"`
	Spectator int32  `protobuf:"varint,7,opt,name=spectators,proto3" json:"spectators,omitempty"`
}

func (m *MsgUpdateMatchInfo) Reset()         { *m = MsgUpdateMatchInfo{} }
func (m *MsgUpdateMatchInfo) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateMatchInfo) ProtoMessage()    {}
func (*MsgUpdateMatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{4}
}
func (m *MsgUpdateMatchInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateMatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateMatchInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateMatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateMatchInfo.Merge(m, src)
}
func (m *MsgUpdateMatchInfo) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateMatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateMatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateMatchInfo proto.InternalMessageInfo

func (m *MsgUpdateMatchInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateMatchInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateMatchInfo) GetMatchdate() string {
	if m != nil {
		return m.Matchdate
	}
	return ""
}

func (m *MsgUpdateMatchInfo) GetHome() string {
	if m != nil {
		return m.Home
	}
	return ""
}

func (m *MsgUpdateMatchInfo) GetAway() string {
	if m != nil {
		return m.Away
	}
	return ""
}

func (m *MsgUpdateMatchInfo) GetStadium() string {
	if m != nil {
		return m.Stadium
	}
	return ""
}

func (m *MsgUpdateMatchInfo) GetSpectators() int32 {
	if m != nil {
		return m.Spectator
	}
	return 0
}

type MsgUpdateMatchInfoResponse struct {
}

func (m *MsgUpdateMatchInfoResponse) Reset()         { *m = MsgUpdateMatchInfoResponse{} }
func (m *MsgUpdateMatchInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateMatchInfoResponse) ProtoMessage()    {}
func (*MsgUpdateMatchInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{5}
}
func (m *MsgUpdateMatchInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateMatchInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateMatchInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateMatchInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateMatchInfoResponse.Merge(m, src)
}
func (m *MsgUpdateMatchInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateMatchInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateMatchInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateMatchInfoResponse proto.InternalMessageInfo

type MsgDeleteMatchInfo struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteMatchInfo) Reset()         { *m = MsgDeleteMatchInfo{} }
func (m *MsgDeleteMatchInfo) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteMatchInfo) ProtoMessage()    {}
func (*MsgDeleteMatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{6}
}
func (m *MsgDeleteMatchInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteMatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteMatchInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteMatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteMatchInfo.Merge(m, src)
}
func (m *MsgDeleteMatchInfo) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteMatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteMatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteMatchInfo proto.InternalMessageInfo

func (m *MsgDeleteMatchInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteMatchInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteMatchInfoResponse struct {
}

func (m *MsgDeleteMatchInfoResponse) Reset()         { *m = MsgDeleteMatchInfoResponse{} }
func (m *MsgDeleteMatchInfoResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteMatchInfoResponse) ProtoMessage()    {}
func (*MsgDeleteMatchInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a80c76a1a8cdb4e, []int{7}
}
func (m *MsgDeleteMatchInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteMatchInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteMatchInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteMatchInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteMatchInfoResponse.Merge(m, src)
}
func (m *MsgDeleteMatchInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteMatchInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteMatchInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteMatchInfoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "match.match.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "match.match.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateMatchInfo)(nil), "match.match.MsgCreateMatchInfo")
	proto.RegisterType((*MsgCreateMatchInfoResponse)(nil), "match.match.MsgCreateMatchInfoResponse")
	proto.RegisterType((*MsgUpdateMatchInfo)(nil), "match.match.MsgUpdateMatchInfo")
	proto.RegisterType((*MsgUpdateMatchInfoResponse)(nil), "match.match.MsgUpdateMatchInfoResponse")
	proto.RegisterType((*MsgDeleteMatchInfo)(nil), "match.match.MsgDeleteMatchInfo")
	proto.RegisterType((*MsgDeleteMatchInfoResponse)(nil), "match.match.MsgDeleteMatchInfoResponse")
}

func init() { proto.RegisterFile("match/match/tx.proto", fileDescriptor_8a80c76a1a8cdb4e) }

var fileDescriptor_8a80c76a1a8cdb4e = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xae, 0xbb, 0xb6, 0x53, 0xbd, 0x89, 0x09, 0xaf, 0xd2, 0xb2, 0xa8, 0xa4, 0x55, 0x84, 0x44,
	0x55, 0xb1, 0x06, 0x86, 0xb4, 0xc3, 0x6e, 0x14, 0x2e, 0x48, 0x54, 0x42, 0x41, 0x5c, 0xe0, 0x30,
	0x99, 0xc6, 0x4b, 0x23, 0x91, 0x38, 0x8a, 0x3d, 0x58, 0x6f, 0x88, 0x23, 0x27, 0x7e, 0x06, 0xc7,
	0x4a, 0x70, 0xe2, 0x17, 0xec, 0xc0, 0x61, 0xe2, 0xc4, 0x09, 0xa1, 0xf6, 0xd0, 0x9f, 0xc0, 0x15,
	0xd9, 0x4e, 0xda, 0xd4, 0x6d, 0xc7, 0xc4, 0xc5, 0xf1, 0xfb, 0xde, 0xf3, 0xf7, 0xbe, 0xcf, 0x76,
	0x0c, 0x6b, 0x21, 0xe6, 0xfd, 0x81, 0xa3, 0x46, 0x7e, 0xde, 0x89, 0x13, 0xca, 0x29, 0xda, 0x92,
	0x71, 0x47, 0x8e, 0xe6, 0x4d, 0x1c, 0x06, 0x11, 0x75, 0xe4, 0xa8, 0xf2, 0xe6, 0x5e, 0x9f, 0xb2,
	0x90, 0x32, 0x27, 0x64, 0xbe, 0xf3, 0xf6, 0xbe, 0xf8, 0xa4, 0x89, 0x7d, 0x95, 0x38, 0x91, 0x91,
	0xa3, 0x82, 0x34, 0x55, 0xf3, 0xa9, 0x4f, 0x15, 0x2e, 0x66, 0x29, 0x6a, 0xe4, 0xfb, 0xc7, 0x38,
	0xc1, 0x61, 0x56, 0x5f, 0xcf, 0x67, 0xe4, 0x78, 0x12, 0x44, 0xa7, 0xe9, 0x3a, 0xfb, 0x0b, 0x80,
	0x3b, 0x3d, 0xe6, 0xbf, 0x88, 0x3d, 0xcc, 0xc9, 0x33, 0xb9, 0x0e, 0x1d, 0xc1, 0x2a, 0x3e, 0xe3,
	0x03, 0x9a, 0x04, 0x7c, 0x68, 0x80, 0x26, 0x68, 0x55, 0xbb, 0xc6, 0x8f, 0xaf, 0x07, 0xb5, 0x54,
	0xc6, 0x43, 0xcf, 0x4b, 0x08, 0x63, 0xcf, 0x79, 0x12, 0x44, 0xbe, 0x3b, 0x2f, 0x45, 0x47, 0xb0,
	0xa2, 0x3a, 0x1b, 0xc5, 0x26, 0x68, 0x6d, 0x1d, 0xee, 0x76, 0x72, 0xf6, 0x3b, 0x8a, 0xbc, 0x5b,
	0xbd, 0xf8, 0xd5, 0x28, 0x7c, 0x9e, 0x8e, 0xda, 0xc0, 0x4d, 0xab, 0x8f, 0xef, 0x7d, 0x98, 0x8e,
	0xda, 0x73, 0x9e, 0x8f, 0xd3, 0x51, 0xfb, 0x96, 0x92, 0x7b, 0x9e, 0xca, 0xd6, 0x14, 0xda, 0xfb,
	0x70, 0x4f, 0x83, 0x5c, 0xc2, 0x62, 0x1a, 0x31, 0x62, 0x7f, 0x03, 0x10, 0xf5, 0x98, 0xff, 0x28,
	0x21, 0x98, 0x93, 0x9e, 0x58, 0xfd, 0x24, 0x3a, 0xa5, 0xc8, 0x80, 0x9b, 0x7d, 0x01, 0xd1, 0x44,
	0x39, 0x72, 0xb3, 0x10, 0xd5, 0x61, 0x55, 0x36, 0x11, 0x5c, 0x52, 0x78, 0xd5, 0x9d, 0x03, 0x08,
	0xc1, 0xd2, 0x80, 0x86, 0xc4, 0xd8, 0x90, 0x09, 0x39, 0x17, 0x18, 0x7e, 0x87, 0x87, 0x46, 0x49,
	0x61, 0x62, 0x2e, 0xf8, 0x19, 0xc7, 0x5e, 0x70, 0x16, 0x1a, 0x15, 0xc5, 0x9f, 0x86, 0x82, 0x9f,
	0xc5, 0xa4, 0xcf, 0x65, 0xef, 0xcd, 0x26, 0x68, 0x95, 0xdd, 0x39, 0x70, 0xbc, 0x2d, 0xbc, 0x67,
	0x5a, 0xec, 0xbb, 0xd0, 0x5c, 0xd6, 0x9e, 0x59, 0x43, 0x37, 0x60, 0x31, 0xf0, 0xa4, 0xfc, 0x92,
	0x5b, 0x0c, 0x3c, 0xfb, 0xbb, 0xb2, 0xaa, 0xb6, 0xe1, 0x3a, 0x56, 0x15, 0x41, 0x31, 0x23, 0x58,
	0xb4, 0xbe, 0xb1, 0xce, 0x7a, 0x69, 0x85, 0xf5, 0xf2, 0xb5, 0xac, 0x5b, 0x10, 0xce, 0x9c, 0xb2,
	0xd4, 0x7b, 0x0e, 0xd1, 0xcc, 0xd7, 0xa5, 0x79, 0xcd, 0xcd, 0xec, 0x5c, 0x9f, 0x4a, 0xaf, 0x8f,
	0xc9, 0x1b, 0xf2, 0x5f, 0x5e, 0x57, 0xf6, 0xd2, 0xd8, 0xb2, 0x5e, 0x87, 0x7f, 0x8a, 0x70, 0xa3,
	0xc7, 0x7c, 0xe4, 0xc2, 0xed, 0x85, 0x1f, 0xa3, 0xbe, 0x70, 0xa1, 0xb5, 0x1b, 0x68, 0xde, 0xbe,
	0x2a, 0x3b, 0x3b, 0xc4, 0x57, 0x70, 0x47, 0xbf, 0x9b, 0x0d, 0x7d, 0xa1, 0x56, 0x60, 0xde, 0xf9,
	0x47, 0x41, 0x9e, 0x5c, 0xbf, 0x0d, 0x8d, 0xd5, 0xaa, 0xae, 0x20, 0x5f, 0x73, 0x02, 0x82, 0x5c,
	0xdf, 0xfe, 0x25, 0x72, 0xad, 0x60, 0x99, 0x7c, 0xcd, 0x96, 0x9b, 0xe5, 0xf7, 0xe2, 0x49, 0xe8,
	0x1e, 0x5c, 0x8c, 0x2d, 0x70, 0x39, 0xb6, 0xc0, 0xef, 0xb1, 0x05, 0x3e, 0x4d, 0xac, 0xc2, 0xe5,
	0xc4, 0x2a, 0xfc, 0x9c, 0x58, 0x85, 0x97, 0xbb, 0x8b, 0x2f, 0x02, 0x1f, 0xc6, 0x84, 0xbd, 0xae,
	0xc8, 0x47, 0xec, 0xc1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x2a, 0xc2, 0x8a, 0x7e, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateMatchInfo(ctx context.Context, in *MsgCreateMatchInfo, opts ...grpc.CallOption) (*MsgCreateMatchInfoResponse, error)
	UpdateMatchInfo(ctx context.Context, in *MsgUpdateMatchInfo, opts ...grpc.CallOption) (*MsgUpdateMatchInfoResponse, error)
	DeleteMatchInfo(ctx context.Context, in *MsgDeleteMatchInfo, opts ...grpc.CallOption) (*MsgDeleteMatchInfoResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/match.match.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateMatchInfo(ctx context.Context, in *MsgCreateMatchInfo, opts ...grpc.CallOption) (*MsgCreateMatchInfoResponse, error) {
	out := new(MsgCreateMatchInfoResponse)
	err := c.cc.Invoke(ctx, "/match.match.Msg/CreateMatchInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateMatchInfo(ctx context.Context, in *MsgUpdateMatchInfo, opts ...grpc.CallOption) (*MsgUpdateMatchInfoResponse, error) {
	out := new(MsgUpdateMatchInfoResponse)
	err := c.cc.Invoke(ctx, "/match.match.Msg/UpdateMatchInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteMatchInfo(ctx context.Context, in *MsgDeleteMatchInfo, opts ...grpc.CallOption) (*MsgDeleteMatchInfoResponse, error) {
	out := new(MsgDeleteMatchInfoResponse)
	err := c.cc.Invoke(ctx, "/match.match.Msg/DeleteMatchInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateMatchInfo(context.Context, *MsgCreateMatchInfo) (*MsgCreateMatchInfoResponse, error)
	UpdateMatchInfo(context.Context, *MsgUpdateMatchInfo) (*MsgUpdateMatchInfoResponse, error)
	DeleteMatchInfo(context.Context, *MsgDeleteMatchInfo) (*MsgDeleteMatchInfoResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateMatchInfo(ctx context.Context, req *MsgCreateMatchInfo) (*MsgCreateMatchInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatchInfo not implemented")
}
func (*UnimplementedMsgServer) UpdateMatchInfo(ctx context.Context, req *MsgUpdateMatchInfo) (*MsgUpdateMatchInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMatchInfo not implemented")
}
func (*UnimplementedMsgServer) DeleteMatchInfo(ctx context.Context, req *MsgDeleteMatchInfo) (*MsgDeleteMatchInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMatchInfo not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/match.match.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateMatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateMatchInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateMatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/match.match.Msg/CreateMatchInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateMatchInfo(ctx, req.(*MsgCreateMatchInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateMatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateMatchInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateMatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/match.match.Msg/UpdateMatchInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateMatchInfo(ctx, req.(*MsgUpdateMatchInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteMatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteMatchInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteMatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/match.match.Msg/DeleteMatchInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteMatchInfo(ctx, req.(*MsgDeleteMatchInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "match.match.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateMatchInfo",
			Handler:    _Msg_CreateMatchInfo_Handler,
		},
		{
			MethodName: "UpdateMatchInfo",
			Handler:    _Msg_UpdateMatchInfo_Handler,
		},
		{
			MethodName: "DeleteMatchInfo",
			Handler:    _Msg_DeleteMatchInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match/match/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateMatchInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateMatchInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateMatchInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Spectator != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Spectator))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Stadium) > 0 {
		i -= len(m.Stadium)
		copy(dAtA[i:], m.Stadium)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Stadium)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Away) > 0 {
		i -= len(m.Away)
		copy(dAtA[i:], m.Away)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Away)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Home) > 0 {
		i -= len(m.Home)
		copy(dAtA[i:], m.Home)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Home)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Matchdate) > 0 {
		i -= len(m.Matchdate)
		copy(dAtA[i:], m.Matchdate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Matchdate)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateMatchInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateMatchInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateMatchInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateMatchInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateMatchInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateMatchInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Spectator != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Spectator))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Stadium) > 0 {
		i -= len(m.Stadium)
		copy(dAtA[i:], m.Stadium)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Stadium)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Away) > 0 {
		i -= len(m.Away)
		copy(dAtA[i:], m.Away)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Away)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Home) > 0 {
		i -= len(m.Home)
		copy(dAtA[i:], m.Home)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Home)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Matchdate) > 0 {
		i -= len(m.Matchdate)
		copy(dAtA[i:], m.Matchdate)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Matchdate)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateMatchInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateMatchInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateMatchInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteMatchInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteMatchInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteMatchInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteMatchInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteMatchInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteMatchInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateMatchInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Matchdate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Home)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Away)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Stadium)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Spectator != 0 {
		n += 1 + sovTx(uint64(m.Spectator))
	}
	return n
}

func (m *MsgCreateMatchInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateMatchInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Matchdate)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Home)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Away)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Stadium)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Spectator != 0 {
		n += 1 + sovTx(uint64(m.Spectator))
	}
	return n
}

func (m *MsgUpdateMatchInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteMatchInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteMatchInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateMatchInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateMatchInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateMatchInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Matchdate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Matchdate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Home", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Home = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Away", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Away = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stadium", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stadium = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spectator", wireType)
			}
			m.Spectator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Spectator |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateMatchInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateMatchInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateMatchInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateMatchInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateMatchInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateMatchInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Matchdate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Matchdate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Home", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Home = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Away", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Away = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stadium", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stadium = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spectators", wireType)
			}
			m.Spectator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Spectator |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateMatchInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateMatchInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateMatchInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteMatchInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteMatchInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteMatchInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteMatchInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteMatchInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteMatchInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
